export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCEED = 'GET_CATEGORY_SUCCEED';
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCEED = 'CREATE_CATEGORY_SUCCEED';


export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCEED = 'UPDATE_CATEGORY_SUCCEED';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCEED = 'DELETE_CATEGORY_SUCCEED';